version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=myappassword
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PROD_DATABASE_URL="postgres://postgres:myappassword@db/myapp_production"
      - DEV_DATABASE_URL="postgres://postgres:myappassword@db/myapp_development"
      - TEST_DATABASE_URL="postgres://postgres:myappassword@db/myapp_test"
  newman:
    image: postman/newman:alpine
    profiles:
      - tests
    volumes:
      - ./test/newman:/etc/newman