name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker-build
        run: docker-compose build

      - name: docker-compose up
        run: docker-compose up -d

      - name: run newman
        run: docker-compose run --rm newman run github-docker-demo.postman_collection.json -e docker.postman_environment.json
