name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker-build
        run: docker-compose build

      - name: docker-compose up
        run: docker-compose up -d

      - name: run newman
        continue-on-error: true
        run: docker-compose run --rm newman run github-docker-demo.postman_collection.json -e docker.postman_environment.json -r cli,junit

      - name: test report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/test/newman/newman/*.xml'
          fail_on_failure: true

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        if: always()
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
