name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker-build
        run: docker-compose build

      - name: docker-compose up
        run: docker-compose up -d

      - name: run newman
        continue-on-error: true
        run: docker-compose run --rm newman run github-docker-demo.postman_collection.json -e docker.postman_environment.json -r cli,junit
      
      - name: ls
        run: ls -lah test/newman/newman/

      - name: test report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: 'test/newman/newman/*.xml'
